#!/bin/sh

KW_DISPLAY=66
KW_SCREEN=0

if ! [ $(pgrep -f "Xvfb :${KW_DISPLAY} -screen ${KW_SCREEN}") ]; then
    Xvfb :${KW_DISPLAY} -screen ${KW_SCREEN} 1024x768x24 -fbdir /tmp > Xvfb.log 2>&1 & 
fi

DISPLAY=:${KW_DISPLAY}.${KW_SCREEN} xulrunner-1.9.2 $@
#xvfb-run -s '-screen 0 1024x768x24' xulrunner application.ini $@
